"""add model file name to robot type

Revision ID: 0decc0e420e7
Revises: b5f91e296db4
Create Date: 2022-07-22 15:45:42.585508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0decc0e420e7'
down_revision = 'b5f91e296db4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generationtemplate', 'version',
               existing_type=sa.REAL(),
               type_=sa.FLOAT(precision=2),
               existing_nullable=False)
    op.add_column('robottype', sa.Column('model_file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robottype', 'model_file_name')
    op.alter_column('generationtemplate', 'version',
               existing_type=sa.FLOAT(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
