"""robot type with generation template reference

Revision ID: 1140f5f756c0
Revises: eb99c7c234fa
Create Date: 2022-07-01 13:43:32.781402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1140f5f756c0'
down_revision = 'eb99c7c234fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robottype', sa.Column('generation_template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'robottype', 'generationtemplate', ['generation_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'robottype', type_='foreignkey')
    op.drop_column('robottype', 'generation_template_id')
    # ### end Alembic commands ###
