"""remove_robot_normal_vector

Revision ID: 4e45bc86c890
Revises: beedead632c9
Create Date: 2022-07-24 03:45:57.364732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e45bc86c890'
down_revision = 'beedead632c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robot', 'position_norm_vector_x')
    op.drop_column('robot', 'position_norm_vector_y')
    op.drop_column('robot', 'position_norm_vector_z')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot', sa.Column('position_norm_vector_z', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('robot', sa.Column('position_norm_vector_y', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('robot', sa.Column('position_norm_vector_x', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
