"""add non-nullable property to welding point columns

Revision ID: 569492230e65
Revises: 8181395e3271
Create Date: 2022-07-07 15:21:43.818813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '569492230e65'
down_revision = '8181395e3271'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generationtemplate', 'version',
               existing_type=sa.REAL(),
               type_=sa.FLOAT(precision=2),
               existing_nullable=False)
    op.alter_column('weldingpoint', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('weldingpoint', 'welding_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('weldingpoint', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('weldingpoint', 'x',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('weldingpoint', 'y',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('weldingpoint', 'z',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('weldingpoint', 'x_original',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('weldingpoint', 'y_original',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('weldingpoint', 'z_original',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('weldingpoint', 'roll',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('weldingpoint', 'pitch',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('weldingpoint', 'yaw',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weldingpoint', 'yaw',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('weldingpoint', 'pitch',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('weldingpoint', 'roll',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('weldingpoint', 'z_original',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('weldingpoint', 'y_original',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('weldingpoint', 'x_original',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('weldingpoint', 'z',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('weldingpoint', 'y',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('weldingpoint', 'x',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('weldingpoint', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('weldingpoint', 'welding_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('weldingpoint', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('generationtemplate', 'version',
               existing_type=sa.FLOAT(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
