"""initial_version

Revision ID: ad7ddf800853
Revises: 
Create Date: 2022-06-21 02:58:21.887198

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ad7ddf800853'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generationtemplate',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('content', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_generationtemplate_id'), 'generationtemplate', ['id'], unique=False)
    op.create_index(op.f('ix_generationtemplate_name'), 'generationtemplate', ['name'], unique=False)
    op.create_table('project',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_table('robottype',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('vendor', sa.String(), nullable=True),
                    sa.Column('capacity_load_kg', sa.Float(), nullable=True),
                    sa.Column('range_m', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_robottype_id'), 'robottype', ['id'], unique=False)
    op.create_index(op.f('ix_robottype_name'), 'robottype', ['name'], unique=False)
    op.create_table('robot',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('robot_type_id', sa.Integer(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['robot_type_id'], ['robottype.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_robot_id'), 'robot', ['id'], unique=False)
    op.create_table('weldingpoint',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=True),
                    sa.Column('robot_id', sa.Integer(), nullable=True),
                    sa.Column('welding_order', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('x', sa.Float(), nullable=True),
                    sa.Column('y', sa.Float(), nullable=True),
                    sa.Column('z', sa.Float(), nullable=True),
                    sa.Column('roll', sa.Float(), nullable=True),
                    sa.Column('pitch', sa.Float(), nullable=True),
                    sa.Column('yaw', sa.Float(), nullable=True),
                    sa.Column('tolerance', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
                    sa.ForeignKeyConstraint(['robot_id'], ['robot.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_weldingpoint_id'), 'weldingpoint', ['id'], unique=False)
    op.create_index(op.f('ix_weldingpoint_welding_order'), 'weldingpoint', ['welding_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weldingpoint_welding_order'), table_name='weldingpoint')
    op.drop_index(op.f('ix_weldingpoint_id'), table_name='weldingpoint')
    op.drop_table('weldingpoint')
    op.drop_index(op.f('ix_robot_id'), table_name='robot')
    op.drop_table('robot')
    op.drop_index(op.f('ix_robottype_name'), table_name='robottype')
    op.drop_index(op.f('ix_robottype_id'), table_name='robottype')
    op.drop_table('robottype')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_generationtemplate_name'), table_name='generationtemplate')
    op.drop_index(op.f('ix_generationtemplate_id'), table_name='generationtemplate')
    op.drop_table('generationtemplate')
    # ### end Alembic commands ###
