name: Build a docker image

on:
  push:
    branches:
    - main
    - automatic-build
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: low-code-ros
  ORGANIZATION: sqe22

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.0.2

    - name: Log in to the Container registry
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate version number
      id: semver
      uses: paulhatch/semantic-version@v4.0.2
      with:
        major_pattern: "/^MAJOR:.*$/"
        format: "${major}-${increment}"
        namespace: ${{ env.GITHUB_SHA }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3.0.0
      with:
        context: ./src
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ env.IMAGE_NAME }}:${{ steps.semver.outputs.version }}"
